### ISSUE TITLE
Latest release jar file has broken Source connector

### ISSUE THREAD

**Issue by syedhassaanahmed** [Azure/toketi-kafka-connect-iothub#10]
[This release jar file](https://github.com/Azure/toketi-kafka-connect-iothub/releases/download/v0.6/kafka-connect-iothub-assembly_2.11-0.6.jar) has broken structure for Source connector. Inside jar, the path `com/microsoft/azure/iot/kafka/connect` contains folder `sink` but not `source` which causes Kafka Connect to not able to load the plugin. It cannot find class `com.microsoft.azure.iot.kafka.connect.source.IotHubSourceConnector` .. Rebuilding the package from source works. Please rebuild it and upload the correct release artifact.

Thanks

**Comment by dluc** [comment]
@varunpuranik @timlaverty FYI

**Comment by cmendible** [comment]
Hi I can confirm that the source connector is working in the latest [jar](https://github.com/Azure/toketi-kafka-connect-iothub/releases/tag/v0.6) even in distributed mode, when specifying the **connector.class** as: 
**com.microsoft.azure.iot.kafka.connect.IotHubSourceConnector** in the configuration.

**Comment by sanyams** [comment]
I ran into this today. I had to update the connect config to remove source from the class name. Looks like the source code has the correct package name but the release jar file is probably not built properly.

This works ... 
connector.class=**com.microsoft.azure.iot.kafka.connect.IotHubSourceConnector**

**Comment by varunpuranik** [comment]
You are right, the jar needs to be updated. I will try to get it done soon..

**Comment by syedhassaanahmed** [comment]
@varunpuranik I've added a PR for CI/CD to avoid these issues in future. Please review.
