### ISSUE TITLE
Error running Kafka connector for IOT Hub

### ISSUE THREAD

**Issue by Mimetis** [Azure/toketi-kafka-connect-iothub#20]
We tried to use the Toketi Kafka Connector​ (The Source Connector) but failed to implement it.

See the repro steps to be able to reproduce the error we get.

### Requirement

- ​Having a running IOT Hub architecture (IOT Edge in our case)
- Having an Azure Kafka HD Insight running

### Uploading Binaries on kafka
​Downloading binaries / conf file, locally
Editing the conf file to match the IOT Hub conf

```
​connector.class=com.microsoft.azure.iot.kafka.connect.source.IotHubSourceConnector
name=AzureIotHubConnector
tasks.max=1
Kafka.Topic=IotTopic
IotHub.EventHubCompatibleName=iothubseb
IotHub.EventHubCompatibleEndpoint=sb://iothub-ns-iothubseb-403463-ff108f0690.servicebus.windows.net/
IotHub.AccessKeyName=service
IotHub.AccessKeyValue=XahyUfVfU1IYJON1dtqW7qG67Oe9HiowX3dcnTrxdk8=
IotHub.ConsumerGroup=$Default
IotHub.Partitions=4
IotHub.StartTime=2018-01-28T00:00:00Z
IotHub.Offsets=
BatchSize=100
ReceiveTimeout=60
```

Then uploading IOT Hub jar & config To Kafka
```
scp kafka-connect-iothub-assembly_2.11-0.6.jar sshuser@kafkatruck-ssh.azurehdinsight.net:/home
/sshuser/
scp connect-iothub-source.properties sshuser@kafkatruck-ssh.azurehdinsight.net:/home/sshuser/​
```
### Copying binaries in the right folder

Connect with SSH on Kafka then copying the files to correct directories:

```
cp kafka-connect-iothub-assembly_2.11-0.6.jar /usr/hdp/current/kafka-broker/libs/
cp connect-iothub-source.properties /usr/hdp/current/kafka-broker/config
```
Go to Kafka config directory
```
cd /usr/hdp/current/kafka-broker
```

Launch the command

​```
bin/connect-standalone.sh config/connect-standalone.properties config/connect-iothub-source.properties
​```

Error raised :

```
could not create Vfs.Dir from url, no matching UrlType was found [file:/usr/hdp/current/kafka-broker/bin/../libs/rolling_upgrade.sh]
java.io.FileNotFoundException: /usr/hdp/current/kafka-broker/bin/../libs/zookeeper.jar
java.io.FileNotFoundException: /usr/hdp/current/kafka-broker/bin/../libs/ojdbc6.jar
org.apache.kafka.connect.errors.ConnectException: Failed to start connector: AzureIotHubConnector
ERROR Failed to start connector AzureIotHubConnector (org.apache.kafka.connect.runtime.Worker:167)
org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches com.microsoft.azure.iot.kafka.connect.source.IotHubSourceConnector, available connectors are: org.apache.kafka.connect.source.SourceConnector, org.apache.kafka.connect.tools.SchemaSourceConnector, org.apache.kafka.connect.sink.SinkConnector, org.apache.kafka.connect.tools.MockConnector, org.apache.kafka.connect.tools.MockSinkConnector, com.microsoft.azure.iot.kafka.connect.IotHubSourceConnector, org.apache.kafka.connect.tools.VerifiableSinkConnector, com.microsoft.azure.iot.kafka.connect.sink.IotHubSinkConnector, org.apache.kafka.connect.file.FileStreamSinkConnector, org.apache.kafka.connect.tools.VerifiableSourceConnector, org.apache.kafka.connect.file.FileStreamSourceConnector, org.apache.kafka.connect.tools.MockSourceConnector​
```

**Comment by ankitkapo** [comment]
Hi Mimetis,
Prebuilt [kafka-connect-iothub-assembly_2.11-0.6.jar](https://github.com/Azure/toketi-kafka-connect-iothub/releases/download/v0.6/kafka-connect-iothub-assembly_2.11-0.6.jar) has some packaging issues. Please build a binary from the source code [(follow this link for the steps)](https://github.com/Azure/toketi-kafka-connect-iothub/blob/master/README_Source.md) and that should fix the issue. You can place the jar file anywhere (not necessarily under KAFKA_HOME/libs) but make sure the configured CLASSPATH environment variable points to this path.

**Comment by sebader** [comment]
@ankitkapo on your point regarding where to place the jar file. If tried the same in multiple ways and did not succeed:
- Place the jar somewhere and edit CLASSPATH env
- Place the jar somewhere and add plugin.path=/my/jar/location in /etc/kafka/conf/connect-standalone.properties
The connector never picked up the jar file. Only when I put it into /usr/hdp/2.6.2.25-1/kafka/libs/ it worked. Any ideas on this behaviour? (I was using Azure HDinsight)

**Comment by ankitkapo** [comment]
@seb-dataworks I also tried this in an HDInsight cluster. Configuring the classpath like "export CLASSPATH=/path/to/my/connectors/*" works well.

**Comment by sebader** [comment]
@ankitkapo does the * matter of the end of the classpath? Don't think I had that in.

**Comment by ankitkapo** [comment]
@seb-dataworks  It does. * is a wild card. It tells run time to search for all Jar files under /path/to/my/connectors/

**Comment by sebader** [comment]
@ankitkapo ok, thanks. Will try this when I find the time

**Comment by nikesh-devaki** [comment]
check if connector.class=com.microsoft.azure.iot.kafka.connect.source.IotHubSourceConnector in config/connect-iothub-source.properties ​file.  "**sources**" subpackage in package name might be missing.

**Comment by inboxtokrish** [comment]
ERROR Error shutting down connector AzureIotHubConnector:  (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:87)
org.apache.kafka.connect.errors.ConnectException: Connector AzureIotHubConnector not found in this worker.

im facing the same error even i placed latest jar. can someone help?

**Comment by nikesh-devaki** [comment]
@inboxtokrish  Double check if "AzureIotHubConnector" in deployed or not.
curl < host > : port/connectors
