### ISSUE TITLE
storing Iot hub secret key in external provider like troll bridge

### ISSUE THREAD

**Issue by balakreshnan** [Azure/toketi-kafka-connect-iothub#21]
So when some one gets access to the connector properties my customer doesn't want to see secret key. they want the secret key to store in external key store like troll bridge or something. This is a big deal with their CISO organization.

**Comment by varunpuranik** [comment]
@balakreshnan I understand the concern, but right now, there is no way you can do this with the this connector. But we will welcome proposals / PRs for supporting such a requirement.
