### ISSUE TITLE
Confusion iwth EventHubCompatibleNamespace property

### ISSUE THREAD

**Issue by dbtucker** [Azure/toketi-kafka-connect-iothub#3]
Could "CompatibleNamespace" property changed to align with the actual value form the portal ... say something like "CompatibleEndpointHost" given that "Endpoint" is used in the Azure Portal for that value.

**Comment by varunpuranik** [comment]
We have fixed this issue. Now the config takes in IotHub.EventHubCompatibleEndpoint which is easily available in the Azure Portal (as specified in the documentation)
