### ISSUE TITLE
Couldnt read from all iothub partitions

### ISSUE THREAD

**Issue by iotgenius** [Azure/toketi-kafka-connect-iothub#6]
Hey Varun,

I followed exact steps but there was one issue, i have 2 partitions on my iothub and source connector reads from just 1 partition not from other one.
I have tried with 1 and 2 partitions in kafka topic.

Please help sort it out.

Thanks

**Comment by varunpuranik** [comment]
Hi, 

In connect-iothub-source.properties, there are 2 properties related to this, can you please check if you have set them properly -
IotHub.Partitions=2
tasks.max=2 
(the second is not required but recommended).

This is assuming you are running the connector in Standalone mode. In case you are using distributed mode, then you will have to make sure the same 2 properties are being set properly in the json payload when you make the rest api call to start the connector.

Thanks,
Varun

**Comment by shailendraksharma** [comment]
# Maximum number of tasks that should be created for this connector.
# More tasks means more parallelism. For optimal performance,
# this should equal the number of Azure IoT Hub partitions
tasks.max=2

# "IoT Hub" >> your hub >> "Endpoints" >> "Events" >> "Partitions"
IotHub.Partitions=2

# The time from which to start retrieving messages from IoTHub.
# The value should be in UTC and in the format yyyy-mm-ddThh:mm:ssZ
# This setting is mutually exclusive with IotHub.Offsets.
# If StartTime is provided, the Offsets value will be ignored.
IotHub.StartTime=2017-02-03T00:00:00Z

# The offsets for each IoTHub partition from which to start retrieving messages
# from IoTHub, as a comma separated string. For example, for 4 partitions,
# the value would be something like "abc,lmn,pqr,xyz".
# This setting is mutually exclusive with IotHub.StartTime.
# If StartTime is provided, the Offsets value will be ignored.
IotHub.Offsets=

# The size of each batch for retrieving entries from IoTHub. The max supported value is 999.
BatchSize=10

Other settings are related to iot hub.

i followed the same as suggested, and yes its a stand alone setup and i tries with multibroker (kafka) on same machine.

still its not clear why its not picking up another partition.

Any help if i am setting up kafka topic wrong to do so?

Thanks

**Comment by varunpuranik** [comment]
A new change has been checked in that displays the partitions of the EventHub that the connector is reading from. I tested it and confirmed that it is indeed reading from all partitions of the test EventHub. 
I will close this issue. If you are able to repro it, please re-open the issue and provide more details.
